### ISSUE TITLE
Misplaced Search Bar on Search Page

### ISSUE THREAD

**Issue by EthanC** [Axel--/Naut-for-reddit#102]
![image](https://cloud.githubusercontent.com/assets/16727756/23531857/25ecec1e-ff6e-11e6-8608-300173bc148a.png)

**Comment by tristinDLC** [comment]
Are you trying to move the "Refine" dropdown? If you want to move it, you can use:

`.res-searchHelper-searchPageTabs ul.res-search-tabs {margin-top: XXpx;padding-left:YYpx;}`

Insert that in the add-on section and set XX and YY to the values you want to get the dropdown in the right spot. You can use just one or even both attributes to move it around, but just a top margin of 50px should get it back to where it was.

**Comment by notderw** [comment]
Are you using the legacy search page?

**Comment by EthanChrisp** [comment]
Search Bar position shifted while RES is enabled.

![image](https://cloud.githubusercontent.com/assets/16727756/26532222/96265c54-43c0-11e7-94ab-ccb7cdda8feb.png)

**Comment by realsrikar** [comment]
I had a similar issue with RES enabled:

<img width="930" alt="screen shot 2017-08-03 at 18 14 11" src="https://user-images.githubusercontent.com/30674879/28946247-e622a8de-7877-11e7-8d38-9e5b78e588fe.png">

## Reproducing:
- RES Enabled
- CSS applied using the chrome extension "Stylish"

## Fix:
`div#previoussearch > form#search > input, div#previoussearch > form#search > label {margin-left: 160px;} .res-searchHelper-searchPageTabs .search-page #search {margin-bottom: 55px;}`

### Here's what it looks like after the code fix:
<img width="762" alt="screen shot 2017-08-03 at 18 33 04" src="https://user-images.githubusercontent.com/30674879/28946754-3593a038-787a-11e7-8fbe-9486555d2eef.png">

**Comment by DuckOfDuckness** [comment]
How come the search page I see doesn't really look like any of the ones you two see?
And also, how come this only seems to be a problem in Firefox?

I see this:

**Chrome**
![chrome_2017-09-23_16-15-01](https://user-images.githubusercontent.com/1951003/30773968-ca58e1be-a07b-11e7-81d8-304f7f74e162.png)
**Firefox**
![firefox_2017-09-23_16-19-30](https://user-images.githubusercontent.com/1951003/30773977-dca59150-a07b-11e7-84a2-c31070fc9679.png)
**Chrome with RES**
![chrome_2017-09-23_16-16-04](https://user-images.githubusercontent.com/1951003/30773973-d664cb1c-a07b-11e7-9efb-ee77a08cab49.png)
**Firefox with RES**
![firefox_2017-09-23_16-24-45](https://user-images.githubusercontent.com/1951003/30773980-e3e262fe-a07b-11e7-807f-25168ea76c1a.png)
