### ISSUE TITLE
Naut Dark unable to see scores in comments

### ISSUE THREAD

**Issue by Taubin** [Axel--/Naut-for-reddit#104]
The points listing next to a users name in comments, is the same color as the background in naut dark. It makes it impossible to read the points score. 
Images:

![](http://i.imgur.com/GgjfXXm.png)

![](http://i.imgur.com/ZNdbN9H.png)

**Comment by EthanChrisp** [comment]
This is an RES Nightmode Error, will be fixed in 4.1.
