### ISSUE TITLE
Subreddit Info on sidebar is weirdly aligned. This fixes the issue.

### ISSUE THREAD

**Issue by thatelijahguy** [Axel--/Naut-for-reddit#105]
.titlebox:before {
    content: "Subreddit Info";
    display: block;
    font-size: 18px;
    font-weight: 700!important;
    text-align: center!important;
    line-height: 24px;
    color: #B92025; (COLOR OF FONT FOR SIDEBAR, AKA H3 HEADING COLOR)
    font-family: arial,helvetica,sans-serif;
    margin: 8px 0;
}

**Comment by EthanChrisp** [comment]
Have a few planned layout changes to the sidebar in Naut 4.1, including the Subreddit Info section :)
