### ISSUE TITLE
Center aligning the search box expando looks better.

### ISSUE THREAD

**Issue by thatelijahguy** [Axel--/Naut-for-reddit#106]
#search #searchexpando {
    text-align: center!important;
}

before aligning/after aligning
stardewvalley vs htgawm

![image](https://cloud.githubusercontent.com/assets/13009943/23633732/f1ddf5ba-0294-11e7-9b77-b4a4faa2ae51.png)

**Comment by EthanChrisp** [comment]
This is more of an opinionated matter, personally I disagree, and I'm not sure if it aligns with Google's Material Design specs, but I'll think about it.
