### ISSUE TITLE
[Suggestion] File readability

### ISSUE THREAD

**Issue by Nefari0uss** [Axel--/Naut-for-reddit#107]
Unless I'm doing something wrong, the entire CSS file is written on a single line making it difficult to modify and maintain. It would greatly benefit from bring properly structured and organized so that it's easier to work with. 

Edit: I'm not sure if the addons section is meant to be just that -- addons, or it's the source of the single massive line of CSS but simply organized. At any rate, a `CONTRIBUTING.md` might be beneficial.

**Comment by gatlinnewhouse** [comment]
https://github.com/Axel--/Naut-for-reddit/blob/master/src/naut_src.css

**Comment by gatlinnewhouse** [comment]
That is the source uncompressed

**Comment by EthanChrisp** [comment]
From the FAQ Image:

> **Why is Naut all on one line?**
> 
> Naut uncompressed greatly exceeds Reddit's 100kb stylesheet limit, without compression you wouldn't be able to use or customize it.

To expand on that, if you'd like to submit contributions via Pull Requests you can do so using the following: https://github.com/Axel--/Naut-for-reddit/blob/master/src/naut_src.css

It is highly advised against editing the source of Naut, as you are likely to cause unmaintainable errors, you're better off adding addons / customization below the main stylesheet line.

**Comment by Nefari0uss** [comment]
Looks like I somehow mistook the css source for also bein a `.psd` file. This is what happens when I look at stuff late during the night. My  bad!
