### ISSUE TITLE
Title input/display inconsistant

### ISSUE THREAD

**Issue by AKDoug** [Axel--/Naut-for-reddit#109]
The input field for title when submitting a post uses text-transform: capitalize. Displaying titles in the list and in the post does not use text-transform: capitalize. This can lead to users inconsistently capitalizing their titles during input, and being disappointed with the display results.

**Comment by EthanChrisp** [comment]
This was fixed in one of the more recent updates, make sure to grab the latest Naut 4 Update via the GitHub Repository and update your stylesheet.
