### ISSUE TITLE
Buggy submit buttons shodow

### ISSUE THREAD

**Issue by flipflop97** [Axel--/Naut-for-reddit#111]
When hovering the submit buttons the shadow grows and then suddenly jumps back to a smaller shadow.
 This only happens to the submit buttons, the search bar for example, doesn't have this problem. [This video](https://zippy.gfycat.com/IncompleteDependentCatbird.webm) shows the bug.

Naut 4.0.5 (no modifications)  
Chrome 58.0.3029.81 (Official Build) (64-bit)

**Comment by drbeat** [comment]
I noticed that too.

It is easily fixed by changing
`.morelink:hover {
box-shadow: 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12), 0 2px 4px -1px rgba(0,0,0,.2);
}`
to
`.morelink:hover {
box-shadow: 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12);
}`
