### ISSUE TITLE
Stray Pixels on Downvote Button (Clicked)

### ISSUE THREAD

**Issue by EthanChrisp** [Axel--/Naut-for-reddit#124]
![image](https://user-images.githubusercontent.com/16727756/30770518-a61e3eee-9ff8-11e7-8d4a-37be2b2204ee.png)

**Comment by Chengers** [comment]
I suspect this is something to do with the image responsible for the downvote arrow selected. I'll take a look at the file and see if the author accidentally left a stray pixel.

**Comment by DuckOfDuckness** [comment]
The stray pixels are from RES's 'set a tag' button:
Below is a cutout of the relevant part of `spritesheet.png`. I've added a background to make it clearer. Cyan line is where the sheet is cut between the pressed downvote and 'set a tag'.
![photoshop_2017-09-24_16-26-22](https://user-images.githubusercontent.com/1951003/30783557-1d1aeedc-a145-11e7-8c11-c459b7cdd262.png)
Just moving 'set a tag' 1 pixel to the right in the spritesheet is not an option, as that just results in 'set a tag' missing 1 column of pixels on the right. Solution will have to be in the CSS.
