### ISSUE TITLE
r/SubName on right hand side overlaps unsub button

### ISSUE THREAD

**Issue by DafsCode** [Axel--/Naut-for-reddit#136]
![image](https://user-images.githubusercontent.com/25325299/37613360-bed2fc80-2b9f-11e8-9588-7253987bfa8c.png)

As seen here.

**Comment by EthanC** [comment]
This isn't a big with Naut. This is caused by the Subreddit name being too long to be displayed correctly in this spot. You could fix this by changing the font size for your subreddit.
