### ISSUE TITLE
header image not shown when adding large banner addon

### ISSUE THREAD

**Issue by Pungent2001** [Axel--/Naut-for-reddit#146]
I pasted the large banner addon and created a banner that was 1920*294 px when I press preview it only shows the blue backdrop. also the advertisement and submission panes overlap
![image](https://user-images.githubusercontent.com/41687535/93236571-accd4200-f787-11ea-9921-b343d066353d.png)

**Comment by notderw** [comment]
It could be RES, but I'm gonna be honest: we haven't really maintained this since new reddit became the defacto so I'm not surprised its all whacked out.  Do you think you could apply it to /r/KFUPM (or a test sub) so I can have a look at it live?

**Comment by Pungent2001** [comment]
> It could be RES, but I'm gonna be honest: we haven't really maintained this since new reddit became the defacto so I'm not surprised its all whacked out. Do you think you could apply it to /r/KFUPM (or a test sub) so I can have a look at it live?

sure, im gonna do that now, check the sub out

**Comment by notderw** [comment]
You are using Naut v3.2, can you try updating the base to the newest version (v4.2)?

**Comment by Pungent2001** [comment]
> You are using Naut v3.2, can you try updating the base to the newest version (v4.2)?

omg, I got the build from the releases tab, that's why I got the old version.. it works now, thank you!

**Comment by notderw** [comment]
sweet!
