### ISSUE TITLE
Multireddit box in wrong place

### ISSUE THREAD

**Issue by RenegadeAI** [Axel--/Naut-for-reddit#25]
Since the subscribe button was moved, the mutireddit box no longer appears in the correct place.

![](http://i.imgur.com/IEDYupq.png)

All that needs to be added is this: 

`.hover-bubble.multi-selector {
margin-top: -70px;
margin-right: -222px;
}`

![](http://i.imgur.com/qofDJoC.png)

**Comment by Axel--** [comment]
Added!
