### ISSUE TITLE
Not an issue, don't know where to ask

### ISSUE THREAD

**Issue by leannecrow** [Axel--/Naut-for-reddit#32]
I'll be honest, I just finished CSS course on code academy and see this awesome Reddit theme completely built using CSS, I find it fascinating. Can you the developers tell about the design process? Did you have some template which you tweaked or had something already existing and converted it into code? Or did you start with a blank page and built it as coding went on?

**Comment by gatlinnewhouse** [comment]
Ask them on /r/Naut
