### ISSUE TITLE
Versioning, Tags, and Releases

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Axel--/Naut-for-reddit#33]
Why aren't you doing some type of versioning for people to easily go back to specific versions like 1.0, 1.7, 2.0, or 3.0?

This would take you back to the exact state in the repo and allow a simple zip download, instead of messy commit tracking for inexperienced users.

**Comment by TheJaredWilcurt** [comment]
Great answer.

**Comment by RenegadeAI** [comment]
None of us have any experience with Git, is there a simple way to implement what you suggested?

He probably closed this since we went through and got rid of all the super old issues from years ago.

**Comment by Foggalong** [comment]
I'd be happy to help out with tagging if needed? We did some retroactive tagging in a project I was working so happy to advise
