### ISSUE TITLE
Submit Text Button Missing

### ISSUE THREAD

**Issue by thenameisnigel** [Axel--/Naut-for-reddit#34]
I was setting up the theme on my sub-reddit, and I disabled links (because it'll be a text-only subreddit) and I noticed that the submit text button is missing? 
![screen shot 2015-03-16 at 10 23 06 pm](https://cloud.githubusercontent.com/assets/2022965/6680265/1c7a3f1a-cc2b-11e4-83e9-b2d3629c54b0.png)
![screen shot 2015-03-16 at 10 23 16 pm](https://cloud.githubusercontent.com/assets/2022965/6680267/2217c47e-cc2b-11e4-9b27-687e177956cc.png)

**Comment by tonybaroneee** [comment]
Did you try the "Submit button for text-only subreddits" addon?

    /* --- Addon: Submit Button fix for text subreddits --- */
        .sidebox.submit.submit-link {display:none;}
        .sidebox.submit.submit-text {display: block;}
    /* --- End Addon --- */

**Comment by thenameisnigel** [comment]
Whoops, I'm slow. Thank you! @tonybaroneee
