### ISSUE TITLE
Add a LICENSE.txt

### ISSUE THREAD

**Issue by razor-x** [Axel--/Naut-for-reddit#40]
Love this theme, but you should really add an explicit license for this. You have over 150 forks. Now that you are part of reddit gold themes, the licensing is even more ambiguous!

http://choosealicense.com/

**Comment by Stephen304** [comment]
+1 This would really help people figure out what they can and cannot do with this theme.

**Comment by evanrelf** [comment]
Yeah, a license would be great! :+1:

**Comment by gatlinnewhouse** [comment]
I suggest an MIT license or GPL

**Comment by kqr** [comment]
A license is really really *really* important. Without it, everyone making a fork are IP pirates breaking copyright law, which is probably not what you want.

**Comment by overactor** [comment]
Make that LICENSE.md MIT seems like a good way to go.
