### ISSUE TITLE
"Sticky Message" bug

### ISSUE THREAD

**Issue by Morgester** [Axel--/Naut-for-reddit#49]
The sticky message customization works great on the homepage of a subreddit (see /r/moto360) but dosen't work so well when viewing the comments.

[Example screenshot.](http://i.imgur.com/k3BEln8.png)

The "content" doesn't appear to push down on any other pages apart from the homepage.

**Comment by KeyworkOrange** [comment]
Try adding "body>.content {margin-top: 132px}" to the addon, it worked for me!

See: https://www.reddit.com/r/naut/comments/3iecsy/issue_with_the_a_sticky_message_above_the_content/

**Comment by KeyworkOrange** [comment]
Try adding 'body>.content {margin-top: 132px}' to the addon, it worked for me!

See: https://www.reddit.com/r/naut/comments/3iecsy/issue_with_the_a_sticky_message_above_the_content/

**Comment by Mxtive** [comment]
This is a /r/Naut 3.2 Issue, please Upgrade to /r/Naut 4.
