### ISSUE TITLE
Top Bar of Subreddits Ends Before Reaching End of Screen

### ISSUE THREAD

**Issue by xd1936** [Axel--/Naut-for-reddit#52]
Why is the top subreddits bar cut off?

![Screenshot1](http://i.imgur.com/RtCihif.png)

![Screenshot2](http://i.imgur.com/KUDWiiF.png)

**Comment by githue** [comment]
The Naut theme sets a width on the user bar that is the same for all users, that username is short so there's room to spare.

**Comment by xd1936** [comment]
Is there an "addon" that sets that whitespace to 0? I love what /r/Android has done. I would love to see that top bar stretch across the whole screen when the userbar is moved down like they have done.

**Comment by githue** [comment]
I don't think so. You can get a browser extension that lets you customize a website's CSS, but you need to know CSS.

**Comment by xd1936** [comment]
I was referring to a "Naut Addon", which is what they call modifications to the Naut CSS. Not a browser Addon or Extension.

https://www.reddit.com/r/naut/wiki/addons

**Comment by xd1936** [comment]
FWIW, [this](https://github.com/xd1936/Naut-for-Reddit-Addons/blob/master/FullScreenSubredditBar.css) was my solution for Naut 3.2 to address this problem
