### ISSUE TITLE
Locked submit button broken

### ISSUE THREAD

**Issue by CaptainBlagbird** [Axel--/Naut-for-reddit#55]
(No add-ons used)
![imgur](https://i.imgur.com/sqOtZGc.png)

**Comment by luisgiii** [comment]
Hi, in order to solve this issue you need to change line 1615.

From: 
.sidebox.submit.submit-link .morelink **a:after** {font-size: 14px; content:"Submit Link";}

to:
.sidebox.submit.submit-link .morelink **a:before** {font-size: 14px; content:"Submit Link";}

**Comment by luisgiii** [comment]
![image](https://cloud.githubusercontent.com/assets/1073155/12616824/95ec16ac-c4d2-11e5-8eb9-bb7c6e473c06.png)

**Comment by EthanChrisp** [comment]
Fixed in the most recent update, thanks!
