### ISSUE TITLE
New subreddit settings for mobile not being styled

### ISSUE THREAD

**Issue by kittsville** [Axel--/Naut-for-reddit#58]
Reddit has added a new settings card to the subreddit settings page. Regular `.linefield` styles are being overridden by native Reddit styles because of their use of the more specific `.linefield.mobile` selector:

![linefield](https://cloud.githubusercontent.com/assets/6013087/12358980/f7e89904-bba7-11e5-8b5d-2f5349170e00.png)

![selector](https://cloud.githubusercontent.com/assets/6013087/12359166/db4e2eb6-bba8-11e5-87f6-c6011a9c9348.png)

Adding `.linefield.mobile` to all selectors with `.linefield` should apply linefield styles to the new settings card.

I found I also had to add `border: none;` to the `/* Subreddit Settings Page + Flair Page + Stylesheet Page */` section to remove the 1px border from the mobile settings tab. This might just apply to the subreddit I tested this on.

**Comment by githue** [comment]
@andytuba:

```
.res-nightmode .linefield.mobile {
	border-color: transparent;
	background-color: hsl(0,0%,10%);
}
```

For /r/resupdates.

**Comment by Mxtive** [comment]
Fixed.
