### ISSUE TITLE
Submit Link/Submit Text Buttons Misaligned

### ISSUE THREAD

**Issue by xd1936** [Axel--/Naut-for-reddit#61]
On Chrome 48 and 49 on Linux, the submit buttons are not centered where they're supposed to be. This issue doesn't happen for me in Firefox on the same machine.

Screenshot:

![Chrome 49/Linux](http://i.imgur.com/Ofcberi.png)

**Comment by RenegadeAI** [comment]
Do you still have this issue?

**Comment by Mxtive** [comment]
Issue closed unless OP still has it? No response in 28 Days.
