### ISSUE TITLE
Icons / spritesheet is not retina / 2x / HiDPI

### ISSUE THREAD

**Issue by phelma** [Axel--/Naut-for-reddit#64]
These ones (might need to view image full size to see on non-retina screens):

![naut_-_a_custom_css_subreddit_theme](https://cloud.githubusercontent.com/assets/4057948/13262463/d9c2874a-da5c-11e5-8296-54a967cb2317.jpg)

Possible solutions:
2x spritesheet (bitmap), SVG icons (vector), custom Icon font (vector)

**Comment by RenegadeAI** [comment]
It would have to be a 2x spritesheet, reddit doesn't allow SVG or custom fonts unfortunately.
