### ISSUE TITLE
Placeholder text

### ISSUE THREAD

**Issue by SteveByerly** [Axel--/Naut-for-reddit#67]
The placeholder text changes don't seem to be applying properly. I get no placeholder text in chrome, and the default in firefox ('search' instead of 'search reddit'). It's also hard to debug since i'm not sure how to see the style rules in-browser for these properties.

I think the text looks good as it is, without replacing contents, etc. I would vote for removing these rules altogether.

**Comment by EthanChrisp** [comment]
Fixed in the most recent update, thanks!
