### ISSUE TITLE
Get rid of the switch to mobile reddit app banner

### ISSUE THREAD

**Issue by gatlinnewhouse** [Axel--/Naut-for-reddit#70]
This could be an addon if you wanted. Below is the css, taken from /u/titleproblems at this [post.](https://www.reddit.com/r/themes/comments/4drprt/riwontswitch_a_reddit_theme_to_disable_the_switch/)

`.mobile-web-redirect-bar,
.mobile-web-redirect {
    display: none;
}`

**Comment by EthanChrisp** [comment]
Not necessarily an issue, feel free to post it on /r/Naut as an addon though.
