### ISSUE TITLE
Logout button overflows when out of room

### ISSUE THREAD

**Issue by EthanChrisp** [Axel--/Naut-for-reddit#84]
Should push the list of subscribed subreddits back, instead. Tends to happen when a user has 5-digit link karma & an unread message. 

Potentially only a lower-res screen issue.

![image](https://cloud.githubusercontent.com/assets/16727756/19344364/7d16bf7a-90ff-11e6-8b8a-7e9a0e2c46a5.png)

**Comment by EthanChrisp** [comment]
Issue still present after latest commit.

Reproduction Steps:

- 1366 x 768 resolution screen
- 5 digit link karma
- 16 character name
- 2 digit unread mail
- New mod mail beta
![image](https://cloud.githubusercontent.com/assets/16727756/20471961/576f819a-af7b-11e6-80ef-4b88c08d9e3f.png)

**Comment by RenegadeAI** [comment]
FUUUUUUUUUUUUUUUUUUUUUUU
