### ISSUE TITLE
Use tags for versioning in GitHub

### ISSUE THREAD

**Issue by drewdotpro** [Axel--/Naut-for-reddit#91]
Seeing as you've released V.4 it would make sense to tag up the V4 release and future major and minors, then use a master branch for your latest, and a develop branch for anything you're working on that could do with contribution.

**Comment by sethwhitaker** [comment]
I would just love to see 4.1 pushed up to a development/beta branch so those of us who develop themes from naut can check it out/use it early.

**Comment by Maltroth** [comment]
Agreed, master should stay as a stable version, since it's becoming more and more used.

**Comment by EthanChrisp** [comment]
We plan to utilize branches in the Rewrite/Naut 5.
